### ISSUE TITLE
Directory `P` is missing.

### ISSUE THREAD

**Issue by martindale** [unsetbit/ozan.io#1]
I'm clicking through some of the links in [P's README](https://github.com/unsetbit/p) (very interesting project, by the way!) and finding 404s.  It seems the folder serving these files no longer exists here in your repo.

**Comment by unsetbit** [comment]
Ah, yes, I went through some rebranding a while back and hadn't upgraded my older projects. Should be fixed now, thanks for bringing it to my attention!
